name: Java CI

# Run CI on all pushes and pull requests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'
          cache: 'maven'

      - name: Run tests and build package
        run: mvn --no-transfer-progress --batch-mode --update-snapshots package

  # Only publish packages when changes are pushed to main branch
  # This prevents publishing from feature branches and PR builds
  publish:
    runs-on: ubuntu-latest
    name: Publish to GitHub Packages
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24 for publishing
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'
          cache: 'maven'

      - name: Configure Maven for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>\${env.GITHUB_ACTOR}</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Publish to GitHub Packages
        run: mvn --no-transfer-progress --batch-mode -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release summary
        run: |
          echo "## 📦 Package Published" >> $GITHUB_STEP_SUMMARY
          echo "Successfully published version $(grep -o '<version>[^<]*</version>' pom.xml | head -1 | sed 's/<version>\(.*\)<\/version>/\1/') to GitHub Packages" >> $GITHUB_STEP_SUMMARY
          echo "- **Repository**: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
